SCR_GroupRolePresetConfig {
 m_sGroupFlagName "undefined"
 m_iGroupSize 0
 m_bIsPrivacyChangeable 0
 m_sGroupRoleName "#AR-GroupRole-Reserves"
 m_aLoadoutResources {
  "{C245589F6844CA36}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Base.et"
  "{968D3819F8506DBE}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Unarmed.et"
 }
}