SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A0348B29431062C}" {
   m_sEntityPrefab "{968D3819F8506DBE}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Unarmed.et"
  }
  SCR_EntityCatalogEntry "{6A432CFAF10058D6}" {
   m_sEntityPrefab "{6913B4118C42D088}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_cadet.et"
  }
  SCR_EntityCatalogEntry "{6A4636D249F33506}" {
   m_sEntityPrefab "{FC7F12590A41B1A1}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Yusupov.et"
  }
  SCR_EntityCatalogEntry "{6A465292D548EF7E}" {
   m_sEntityPrefab "{FC7F12590A41B1A2}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Khamidov.et"
  }
 }
}