SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A0348B29431062C}" {
   m_sEntityPrefab "{968D3819F8506DBE}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Unarmed.et"
  }
  SCR_EntityCatalogEntry "{6A432CFAF10058D6}" {
   m_sEntityPrefab "{6913B4118C42D088}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_cadet.et"
  }
  SCR_EntityCatalogEntry "{6A4636D249F33506}" {
   m_sEntityPrefab "{FC7F12590A41B1A1}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Yusupov.et"
  }
  SCR_EntityCatalogEntry "{6A465292D548EF7E}" {
   m_sEntityPrefab "{FC7F12590A41B1A2}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Khamidov.et"
  }
  SCR_EntityCatalogEntry "{6A7511CA90A82ECE}" {
   m_sEntityPrefab "{79ABD7F0DC9C8697}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Gov_Militia_1.et"
  }
  SCR_EntityCatalogEntry "{6A7511C777935698}" {
   m_sEntityPrefab "{0D34D9ABCB2D429F}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Gov_Militia_2.et"
  }
  SCR_EntityCatalogEntry "{6A7511C7726DAF20}" {
   m_sEntityPrefab "{E8A89552C7C8D5F5}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Gov_Militia_3.et"
  }
  SCR_EntityCatalogEntry "{6A7511C771605F2F}" {
   m_sEntityPrefab "{E8A89552C7C8D5F4}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Militia_Gren.et"
  }
  SCR_EntityCatalogEntry "{6A7511C76CF8EBC8}" {
   m_sEntityPrefab "{114D02D2B7430565}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Militia_MG.et"
  }
 }
}