SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A0348B29431062C}" {
   m_sEntityPrefab "{968D3819F8506DBE}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Unarmed.et"
  }
 }
}