SCR_EntityCatalogMultiList {
 m_eEntityCatalogType VEHICLE
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A0348B501233224}" {
   m_sIdentifier "Vehicles"
   m_aEntities {
    SCR_EntityCatalogEntry "{6A0348B579BFB520}" {
     m_sEntityPrefab "{930E0A8149935FDC}Prefabs/Vehicles/Wheeled/BRDM2/BRDM2_SPAG.et"
    }
   }
  }
 }
}