SCR_ArsenalItemListConfig {
 m_aArsenalItems {
  SCR_ArsenalItemStandalone "{6A10178FDFF87839}" {
   m_eItemType TORSO
   m_iSupplyCost 0
   m_ItemResourceName "{AA4671D72058A45C}Prefabs/Characters/Uniforms/M88_Jacket_SPAG.et"
  }
  SCR_ArsenalItemStandalone "{6A10178F4D6B227B}" {
   m_eItemType TORSO
   m_iSupplyCost 0
   m_ItemResourceName "{43AD25D84C82BE89}Prefabs/Characters/Uniforms/M88_Jacket_Rolledup_SPAG.et"
  }
  SCR_ArsenalItemStandalone "{6A10178F44605D66}" {
   m_eItemType LEGS
   m_iSupplyCost 0
   m_ItemResourceName "{BF4654AEACE767CC}Prefabs/Characters/Uniforms/M88_Pants_SPAG.et"
  }
  SCR_ArsenalItemStandalone "{6A101788ECDB1BAF}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{2C48D6E473271FD6}Prefabs/Items/Equipment/Patches/Patch_Spagistan_Flag_embroidered.et"
  }
  SCR_ArsenalItemStandalone "{6A101788B7FD309F}" {
   m_eItemType HEADWEAR
   m_iSupplyCost 0
   m_ItemResourceName "{E53BD75FE6B81A51}Prefabs/Characters/HeadGear/Helmet_Kiver_RSP/Headgear_Kiver_RSP_cover_spag.et"
  }
 }
}