SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A7B13991B8C9488}" {
   m_sEntityPrefab "{79ABD7F0DC9C8697}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Militia_1.et"
  }
  SCR_EntityCatalogEntry "{6A7B13991B8C936A}" {
   m_sEntityPrefab "{0D34D9ABCB2D429F}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Militia_2.et"
  }
  SCR_EntityCatalogEntry "{6A7B13991B8C9368}" {
   m_sEntityPrefab "{E8A89552C7C8D5F5}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Militia_3.et"
  }
  SCR_EntityCatalogEntry "{6A7B13991B8C9357}" {
   m_sEntityPrefab "{E8A89552C7C8D5F4}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Militia_Gren.et"
  }
  SCR_EntityCatalogEntry "{6A7B139F850BC7ED}" {
   m_sEntityPrefab "{114D02D2B7430565}Prefabs/Characters/Factions/SPAGISTAN/Militia/Character_SPAG_Militia_MG.et"
  }
 }
}