StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6A4623C24803DDA4}" {
   Id "spag-EditableEntity_FlagPole_02_V2_SPAG_Name"
   Target_en_us "Stick Flag Pole - Spagistan"
   Modified 1782995328
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A5A869D4746B722}" {
   Id "spag-Headgear_Helmet_SSh68_Name"
   Target_en_us "SSh68 - Spagpat"
   Modified 1784318027
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A4E5361222BEED6}" {
   Id "spag-Headgear_PatrolCap_spagpat_Name"
   Target_en_us "Patrol Cap - Spagpat"
   Modified 1783519760
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A453B7A65A39639}" {
   Id "spag-Headquarters"
   Target_en_us "Headquarters"
   Modified 1782922701
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A465291737DAE7B}" {
   Id "spag-Khamidov"
   Target_en_us "Khamidov"
   Modified 1782995337
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A453B7BD1D89E95}" {
   Id "spag-Reserves"
   Target_en_us "Reserves"
   Modified 1782922694
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A460367879C076F}" {
   Id "spag-Role_Cadet"
   Target_en_us "Garmsar Cadet"
   Modified 1782978845
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A5A869D61DBCE8E}" {
   Id "spag-Role_Conscript"
   Target_en_us "Conscript"
   Modified 1784318038
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A453B7BBD22D280}" {
   Id "spag-Squad_1"
   Target_en_us "Squad 1"
   Modified 1782922655
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A453B7BA6889D24}" {
   Id "spag-Squad_2"
   Target_en_us "Squad 2"
   Modified 1782922672
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A453B7BAC5B6E92}" {
   Id "spag-Support"
   Target_en_us "Support"
   Modified 1782922681
   Author "Aidan"
   LastChanged "Aidan"
  }
  CustomStringTableItem "{6A5A1EF6C8313A8C}" {
   Id "spag-Vest_Taktika_coy_Name"
   Target_en_us "Plate Carrier - Spagpat/Coyote"
   Modified 1784298692
   Author "aidan"
   LastChanged "aidan"
  }
  CustomStringTableItem "{6A4636D264D6A745}" {
   Id "spag-Yusupov"
   Target_en_us "Yusupov"
   Modified 1782987808
   Author "Aidan"
   LastChanged "Aidan"
  }
 }
}