SCR_CampaignFaction {
 FactionKey "SPAG"
 FactionColor 0 0.44 0.078 1
 UIInfo SCR_FactionUIInfo "{6A07010D86AEE622}" {
  Name "Spagistan Armed Forces"
  Description "The cadets, national guard, and professional armed forces of the nation of Spagistan."
  Icon "{6DA14C32E0DA14D5}UI/Textures/Flags/EditableEntity_Faction_Spag.edds"
  m_sNameUpper "SPAGISTAN ARMED FORCES"
 }
 "Identity of soldiers" FactionIdentity "{6A07010D1ADA73A2}" : "{FBBCD73926989580}Configs/Identities/FactionIdentity_USSR.conf" {
 }
 "Radio encryption key" "litCigarette"
 m_iOrder 1001
 m_OutlineFactionColor 0.001 0.082 0.023 1
 m_NotificationFactionColor 0 0.44 0.078 1
 m_NotificationTextFactionColor 0 0.296 0.055 1
 m_sFactionFlag "{02E99379E5C04A29}UI/Textures/Flags/flag_spag_ca.edds"
 m_FactionFlagMaterial "{B7A02313829700F9}Assets/Props/Fabric/Flags/Data/Flag_1_2_Green.emat"
 m_FactionLabel FACTION_SPAGISTAN
 m_aFriendlyFactionsIds {
  "USSR"
 }
 m_eDefaultGroupRoleForNewGroup NONE
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{6A0CE970ED3478AB}" : "{2D0A12266577D237}Configs/EntityCatalog/SPAG/InventoryItems_EntityCatalog_SPAG.conf" {
  }
 }
 m_aGroupFlags {
  ""
 }
 m_sGroupFlagsImageSet "{301FC1A2A46D3E0D}UI/Textures/GroupManagement/FlagIcons/GroupFlagsIndfor.imageset"
 m_sGroupFlagsImageSetOutlines "{C07D82625600BA21}UI/Textures/GroupManagement/FlagIcons/GroupFlagsIndfor-outline.imageset"
 m_aFlagNames {
  "infantry"
  "amphibious"
  "anti-air"
  "anti-air-artilery"
  "anti-armor-motorized"
  "antiarmor"
  "armored"
  "artillery"
  "combined"
  "helicopter"
  "helicopter-attack"
  "infantry-air"
  "machinegun"
  "maintenance"
  "medical"
  "mortar"
  "motorized"
  "motorized-infantry"
  "recon"
  "recon-motorized"
  "signal"
  "sniper"
  "supply-motorized"
  "undefined"
  "commander"
 }
 m_sFactionBackground "{940C7C9901831ABE}UI/Textures/DeployMenu/Loadout-BG/Loadout_BG_Spagistan.imageset"
 m_MobileHQPrefab "{E171C9F443958371}Prefabs/MP/Campaign/Assets/CampaignMobileAssemblyEast.et"
 m_RadioPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
}