SCR_Faction {
 FactionKey "SPAG"
 FactionColor 0 0.44 0.078 1
 UIInfo SCR_FactionUIInfo "{69F77A8AEB24BF7F}" {
  Name "Spagistan Armed Forces"
  Description "The cadets, national guard, and professional armed forces of the nation of Spagistan."
  Icon "{6DA14C32E0DA14D5}UI/Textures/Flags/EditableEntity_Faction_Spag.edds"
  m_sNameUpper "SPAGISTAN ARMED FORCES"
 }
 "Identity of soldiers" FactionIdentity "{69F77A88A3F8EFF7}" : "{F27B11DDB3EB1D7C}Configs/Identities/FactionIdentity_SPAG.conf" {
 }
 "Radio encryption key" "coldBorscht"
 m_iOrder 1001
 m_OutlineFactionColor 0.001 0.082 0.023 1
 m_NotificationFactionColor 0 0.44 0.078 1
 m_NotificationTextFactionColor 0 0.296 0.055 1
 m_sFactionFlag "{02E99379E5C04A29}UI/Textures/Flags/flag_spag_ca.edds"
 m_FactionFlagMaterial "{6E9DA07CBCE6BE80}Assets/Props/Fabric/Flags/Data/Flag_1_2_Spag.emat"
 m_FactionLabel FACTION_USSR
 m_aFriendlyFactionsIds {
  "USSR"
 }
 m_CallsignInfo SCR_FactionCallsignInfo "{6A453938B49612D0}" : "{05165110CE835CB2}Configs/Callsigns/Callsigns_SPAG.conf" {
 }
 m_aPredefinedGroups {
  SCR_GroupPreset "{7A1E4C9B2D3F5061}" {
   m_eGroupRole COMMANDER
   m_sGroupFlagName "commander"
   m_sGroupDescription "Company and platoon leadership, as well as habitual attachments to the company or platoon."
   m_iGroupSize 12
  }
  SCR_GroupPreset "{7A1E4C9B2D3F5062}" {
   m_eGroupRole ASSAULT
   m_sGroupFlagName "infantry"
   m_sGroupDescription "Infantry rifle squads are the main effort of the Spagistan Armed Forces. They close with the enemy using fire and maneuver."
   m_iGroupSize 12
  }
  SCR_GroupPreset "{7A1E4C9B2D3F5063}" {
   m_eGroupRole SF_ASSAULT
   m_sGroupFlagName "infantry"
   m_sGroupDescription "Typically a rifle squad, Squad 2 is sometimes organized as a weapons squad. The weapons squad's job is to provide the base of fire for the infantry platoon's maneuver."
   m_iGroupSize 12
  }
  SCR_GroupPreset "{7A1E4C9B2D3F5064}" {
   m_eGroupRole MACHINEGUN
   m_sGroupFlagName "machinegun"
   m_sGroupDescription "Support elements who need their own radio frequency for long transmissions, such as artillery or air support."
   m_iGroupSize 6
  }
  SCR_GroupPreset "{7A1E4C9B2D3F5065}" {
   m_eGroupRole RESERVES
   m_sGroupFlagName "undefined"
   m_iGroupSize 0
  }
 }
 m_eDefaultGroupRoleForNewGroup NONE
 m_bEnableAutoGroupCreationWhenFull 0
 m_iFactionRadioFrequency 42000
 m_FactionRankInfo SCR_RankContainer "{6A4548320AE37FAC}" : "{5DFDD1EB1E5A07AF}Configs/Ranks/BaseMilitaryRanks.conf" {
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{6A454832790575E4}" : "{347F47DA486B78DE}Configs/EntityCatalog/SPAG/Characters_EntityCatalog_SPAG.conf" {
  }
  SCR_EntityCatalogMultiList "{6A4548327D242480}" : "{38895D2FE69B243F}Configs/EntityCatalog/SPAG/SPAG_InventoryItems_EntityCatalog.conf" {
  }
  SCR_EntityCatalogMultiList "{6A4548326AF59C62}" : "{D1A807E285B550AB}Configs/EntityCatalog/SPAG/Vehicles_EntityCatalog_SPAG.conf" {
  }
 }
 m_sGroupFlagsImageSet "{301FC1A2A46D3E0D}UI/Textures/GroupManagement/FlagIcons/GroupFlagsIndfor.imageset"
 m_sGroupFlagsImageSetOutlines "{C07D82625600BA21}UI/Textures/GroupManagement/FlagIcons/GroupFlagsIndfor-outline.imageset"
 m_aFlagNames {
  "infantry"
  "amphibious"
  "anti-air"
  "anti-air-artilery"
  "anti-armor-motorized"
  "antiarmor"
  "armored"
  "artillery"
  "combined"
  "helicopter"
  "helicopter-attack"
  "infantry-air"
  "machinegun"
  "maintenance"
  "medical"
  "mortar"
  "motorized"
  "motorized-infantry"
  "recon"
  "recon-motorized"
  "signal"
  "sniper"
  "supply-motorized"
  "undefined"
  "commander"
 }
 m_sFactionBackground "{940C7C9901831ABE}UI/Textures/DeployMenu/Loadout-BG/Loadout_BG_Spagistan.imageset"
 m_iIdentityVoiceSignal 100
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{6A454831706F8C0E}" : "{B905442CCDA6D46D}Configs/Identities/Territories/FactionHomeTerritory_SPAG.conf" {
 }
}