SCR_PlaceableEntitiesRegistry {
 m_sAddon "SpagistanArmedForces"
 m_sSourceDirectory "{AB9D5620D7057364}PrefabsEditable/Auto/Compositions"
 m_Prefabs {
  "{64BD5402093EDD2D}PrefabsEditable/Auto/Compositions/Misc/CustomEntities/InteractionPoints/E_ArsenalBox_SPAG_NoAffiliation.et"
  "{1BA3DC05FFD309BC}PrefabsEditable/Auto/Compositions/Misc/CustomEntities/InteractionPoints/E_ArsenalBox_SPAG_Weapons_NoAffiliation.et"
  "{8A3B0C21794E445A}PrefabsEditable/Auto/Compositions/Misc/CustomEntities/InteractionPoints/E_ArsenalBox_SPAG_equipment_NoAffiliation.et"
 }
}