SCR_PlaceableEntitiesRegistry {
 m_sAddon "SpagistanArmedForces"
 m_sSourceDirectory "{F2F69B95596F0E21}PrefabsEditable/Auto/Props"
 m_Prefabs {
  "{78C5751B4CFD4AF7}PrefabsEditable/Auto/Props/Military/Arsenal/ArsenalBoxes/SPAG/E_ArsenalBox_SPAG.et"
 }
}