SCR_PlaceableEntitiesRegistry {
 m_sAddon "SpagistanArmedForces"
 m_sSourceDirectory "{F2F69B95596F0E20}PrefabsEditable/Auto/Props"
 m_Prefabs {
  "{78C5751B4CFD4AF7}PrefabsEditable/Auto/Props/Military/Arsenal/ArsenalBoxes/SPAG/E_ArsenalBox_SPAG.et"
  "{64BD5402093EDD2D}PrefabsEditable/Auto/Compositions/Misc/CustomEntities/InteractionPoints/E_ArsenalBox_SPAG_NoAffiliation.et"
 }
}