MCF_Device_ProfilesConfig {
 m_aProfiles {
  MCF_Device_Profile "{6A7D3B4BA4773F3F}" {
   m_sId "spag_training"
   m_sDeviceName "Training PC"
   m_eShell LAPTOP
   m_aApps {
    MCF_Device_App "{6A7D3B4BD6FB92A4}" {
     m_eKind FILES
     m_sLabel "Training Documents"
     m_aItems {
      MCF_Device_Item "{6A7D3B4BD986DE91}" {
       m_sHeading "squad_column.pdf"
       m_sBody "The squad column is the squad’s main formation for movement unless preparing for an assault. It provides good dispersion both laterally and in-depth without sacrificing control. It also facilitates maneuver. The lead fire team is the base fire team. Squads can move in either a column wedge (squad column-team wedge) or a modified column wedge. A modified column wedge occurs when rough terrain, poor visibility, and other factors require the squad to modify the wedge into a file for control purposes. As the terrain becomes less rugged and control becomes easier, the Soldiers resume their original positions."
       m_sImage "{EFFB921706B66FF3}Assets/Images/squadColumn.edds"
      }
      MCF_Device_Item "{6A7D3B49745C7549}" {
       m_sHeading "rolling_t.pdf"
       m_sBody "The rolling T is a four-person combat formation used by military infantry to safely navigate narrow hallways and rooms during close-quarters battle."
       m_sImage "{F56A6D1DA91B1160}Assets/Images/urbanRoll.edds"
      }
      MCF_Device_Item "{6A7D3B4622A6A644}" {
       m_sHeading "operations_order.pdf"
       m_sBody "A five-paragraph order (often called an OPORD) is a structured military format used to issue clear, concise operational directions to subordinates. It is commonly remembered by the acronym OSMEAC: Orientation, Situation, Mission, Execution, Administraction & Logistics, and Command & Signal."
       m_sImage "{0DF91F5F4440D888}Assets/Images/OPORD.edds"
      }
     }
    }
   }
  }
 }
}