MCF_Device_ProfilesConfig {
 m_aProfiles {
  MCF_Device_Profile "{6A7C430B9D1CD8BC}" {
   m_sId "spag_training"
   m_sDeviceName "Training PC"
   m_eShell LAPTOP
   m_aApps {
    MCF_Device_App "{6A7C430B112EF474}" {
     m_eKind FILES
     m_sLabel "Training Documents"
     m_aItems {
      MCF_Device_Item "{6A7C4308970BDE84}" {
       m_sHeading "Squad_Column.pdf"
       m_sTimestamp "timestamp!"
       m_sBody "body text!"
      }
     }
    }
    MCF_Device_App "{6A7C4306BD0E2DA4}" {
     m_eKind FILES
     m_aItems {
      MCF_Device_Item "{6A7C4306B2FBF5B4}" {
       m_sHeading "Rolling T Formation"
       m_sBody "Used for moving through corridors or exceptionally complex urban terrain."
      }
     }
    }
   }
  }
 }
}