SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{6A432CFE58A9EFE0}" {
   m_Info SCR_UIInfo "{6A432CFE58A9EE2A}" {
    Name "Spagistan"
    Icon "{6DA14C32E0DA14D5}UI/Textures/Flags/EditableEntity_Faction_Spag.edds"
   }
   m_Order 3
   m_LabelType FACTION_SPAGISTAN
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
 }
}