SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{6A0348A2A55A134C}" {
   m_Info SCR_UIInfo "{6A0348A294E55C2F}" {
    Name "Spagistan"
    Icon "{6DA14C32E0DA14D5}UI/Textures/Flags/EditableEntity_Faction_Spag.edds"
   }
   m_LabelType FACTION_SPAGISTAN
   m_LabelGroupType FACTION
  }
 }
}