SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{6A432CFE58A9EFE0}" {
   m_Info SCR_UIInfo "{6A432CFE58A9EE2A}" {
    Name "Spagistan"
    Description "The cadets, national guard, and professional armed forces of the nation of Spagistan."
    Icon "{6DA14C32E0DA14D5}UI/Textures/Flags/EditableEntity_Faction_Spag.edds"
   }
   m_Order 3
   m_LabelType FACTION_SPAGISTAN
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{6A7B139FFACC3F22}" {
   m_Info SCR_UIInfo "{6A7B139FFACC3FEE}" {
    Name "Spagistani Militia"
    Description "A militarized tribe of Spagistanis. While officially apart of the military, they may have their own interests."
    Icon "{958DEA82A84B2337}UI/Textures/Flags/EditableEntity_Faction_spagmilitia.edds"
   }
   m_Order 4
   m_LabelType FACTION_SPAGMILITIA
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
 }
}