SCR_FactionHomeTerritoryConfig {
 m_aFactionHomeTerritories {
   SCR_FactionHomeTerritory "{6A154EBB523BED87}" {
    m_sID "Anar"
    m_UIInfo SCR_UIInfo "{6A154EBB523BEE6D}" {
     Name "Anar"
    }
   }
   SCR_FactionHomeTerritory "{69F77A954EE7B107}" {
    m_sID "Chak Chak"
    m_UIInfo SCR_UIInfo "{69F77A9484CA9B87}" {
     Name "Chak Chak"
    }
   }
   SCR_FactionHomeTerritory "{69F77A9567D5990A}" {
    m_sID "Feruz Abad"
    m_UIInfo SCR_UIInfo "{69F77A94C181A1A3}" {
     Name "Feruz Abad"
    }
   }
   SCR_FactionHomeTerritory "{6A154EBB4B13D3FD}" {
    m_sID "Garmarud"
    m_UIInfo SCR_UIInfo "{6A154EBB4B13D450}" {
     Name "Garmarud"
    }
   }
   SCR_FactionHomeTerritory "{6A154EB8BD3809DA}" {
    m_sID "Garmsar"
    m_UIInfo SCR_UIInfo "{6A154EB8BD3809B8}" {
     Name "Garmsar"
    }
   }
   SCR_FactionHomeTerritory "{6A154EB8905ADFFA}" {
    m_sID "Loy Manara"
    m_UIInfo SCR_UIInfo "{6A154EB8905AC045}" {
     Name "Loy Manara"
    }
   }
   SCR_FactionHomeTerritory "{6A154EB81386C303}" {
    m_sID "Sakhe"
    m_UIInfo SCR_UIInfo "{6A154EB81386C3FF}" {
     Name "Sakhe"
    }
   }
   SCR_FactionHomeTerritory "{6A154EB834A78666}" {
    m_sID "Shukurkalay"
    m_UIInfo SCR_UIInfo "{6A154EB834A78637}" {
     Name "Shukurkalay"
    }
   }
   SCR_FactionHomeTerritory "{6A154EB824CB79FC}" {
    m_sID "Timurkalay"
    m_UIInfo SCR_UIInfo "{6A154EB824CB7A36}" {
     Name "Timurkalay"
    }
   }
   SCR_FactionHomeTerritory "{69F77A8AA4B828BF}" {
    m_sID "Rasman"
    m_UIInfo SCR_UIInfo "{69F77A949F23F61C}" {
     Name "Rasman"
    }
   }
  }
  m_fSharedPlaceOfBirthWeight 0.6
 }