SCR_PlaceableEntitiesRegistry {
 m_sAddon "SpagistanArmedForces"
 m_sSourceDirectory "{A833B606DC36B1D5}Prefabs/Characters/Factions/SPAG_MILITIA"
 m_Prefabs {
  "{79ABD7F0DC9C8697}Prefabs/Characters/Factions/SPAG_MILITIA/Character_SPAG_Militia_1.et"
  "{0D34D9ABCB2D429F}Prefabs/Characters/Factions/SPAG_MILITIA/Character_SPAG_Militia_2.et"
  "{E8A89552C7C8D5F5}Prefabs/Characters/Factions/SPAG_MILITIA/Character_SPAG_Militia_3.et"
  "{E8A89552C7C8D5F4}Prefabs/Characters/Factions/SPAG_MILITIA/Character_SPAG_Militia_Gren.et"
  "{114D02D2B7430565}Prefabs/Characters/Factions/SPAG_MILITIA/Character_SPAG_Militia_MG.et"
 }
}