SCR_PlaceableEntitiesRegistry {
 m_sAddon "SpagistanArmedForces"
 m_sSourceDirectory "{B225CC09504F2E07}Prefabs/Characters/Factions/SPAGISTAN"
 m_Prefabs {
  "{968D3819F8506DBE}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Unarmed.et"
  "{6913B4118C42D088}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_cadet.et"
  "{FC7F12590A41B1A1}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Yusupov.et"
  "{FC7F12590A41B1A2}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Khamidov.et"
  "{0EC92623613C396C}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_gendarmerie.et"
 }
}