SCR_PlaceableEntitiesRegistry {
 m_sAddon "SpagistanArmedForces"
 m_sSourceDirectory "{B225CC09504F2E07}Prefabs/Characters/Factions/SPAGISTAN"
 m_Prefabs {
  "{968D3819F8506DBE}Prefabs/Characters/Factions/SPAGISTAN/Character_SPAG_Unarmed.et"
 }
}