SCR_PlaceableEntitiesRegistry {
 m_sAddon "SpagistanArmedForces"
 m_sSourceDirectory "{F9291FCE0C1F7605}Prefabs/Vehicles"
 m_Prefabs {
  "{930E0A8149935FDC}Prefabs/Vehicles/Wheeled/BRDM2/BRDM2_SPAG.et"
  "{4D9F072F9278FA0F}Prefabs/Vehicles/Wheeled/BTR70/BTR70_SPAG.et"
  "{D3BD53ED8C9C08D4}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_PKM_SPAG.et"
  "{C831819D3CE40C95}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_SPAG.et"
  "{C9649B72BBFB4936}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_uncovered_SPAG.et"
  "{C21B0A7FF7B486C9}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_ammo_SPAG.et"
  "{9D897671126C640F}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_Arsenal_SPAG.et"
  "{AB9600D95992E3E9}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_command_SPAG.et"
  "{CC10F3AE07E38A46}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_engineer_SPAG.et"
  "{DDFB726718427EC2}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_repair_SPAG.et"
  "{04151C17D97708A3}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_SPAG.et"
  "{A4B5C29AA368C140}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_tanker_SPAG.et"
  "{135F5BD006E2099A}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_transport_covered_SPAG.et"
  "{60C24063B2FA783A}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_transport_SPAG.et"
 }
}