EditablePrefabsComponent_EditableEntity {
 m_EntityLabelRules {
  EditablePrefabsLabel_Faction "{6A0348A21E062445}" {
   m_Label FACTION_SPAGISTAN
   m_FactionToCheck "SPAG"
  }
  EditablePrefabsLabel_Faction "{6A7B139FD5E40BBE}" {
   m_Label FACTION_SPAGMILITIA
   m_FactionToCheck "SPAG_MILITIA"
  }
 }
}