FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{6152787462E15638}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{F4016BBC1A1AB199}Prefabs/Characters/Heads/Head_Persian_01.et"
   Headcamo {
    "{9A4893348B1AB242}Prefabs/Characters/Heads/Head_Persian_01_camo.et"
   }
   Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  VisualIdentity "{6152787462BDBBA3}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{E2831DCA832A685C}Prefabs/Characters/Heads/Head_Persian_02.et"
   Headcamo {
    "{9456D77CB6EDBD98}Prefabs/Characters/Heads/Head_Persian_02_camo.et"
   }
   Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  VisualIdentity "{615278746177680D}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{071F51338FCFFF37}Prefabs/Characters/Heads/Head_Persian_03.et"
   Headcamo {
    "{91A314BB5DBF472E}Prefabs/Characters/Heads/Head_Persian_03_camo.et"
   }
   Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  VisualIdentity "{6A07010181A7F0A4}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{24D28E910BF9F648}Prefabs/Characters/Heads/Head_Asian_02.et"
   Headcamo {
    "{FF94E9F1DAB8496C}Prefabs/Characters/Heads/Head_Asian_02/Head_Asian_02_camo_US_01.et"
    "{3966587EF4BE834D}Prefabs/Characters/Heads/Head_Asian_02/Head_Asian_02_camo_US_02.et"
   }
   Body "{32B5FE236D152368}Prefabs/Characters/Basebody/CharacterBasebody_Asian_02.et"
  }
  VisualIdentity "{6A070101CFE4A3E5}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{EAF055495BA85CA1}Prefabs/Characters/Heads/Head_White_02.et"
   Headcamo {
    "{43AA5BDFE4338F57}Prefabs/Characters/Heads/Head_White_02/Head_White_02_camo_US_01.et"
    "{2FFE6F3F58F70079}Prefabs/Characters/Heads/Head_White_02/Head_White_02_camo_US_02.et"
   }
  }
 }
 SoundIdentityArray {
  SoundIdentity "{6A070102610C7045}" {
   VoiceID 101
   VoicePitch 0
  }
  SoundIdentity "{6A07010242F4EBAB}" {
   VoiceID 101
   VoicePitch 0.8
  }
  SoundIdentity "{6A070101B8B93C97}" {
   VoiceID 101
   VoicePitch -1
  }
  SoundIdentity "{6A070101B3FEC293}" {
   VoiceID 102
  }
  SoundIdentity "{6A070101AC7A579A}" {
   VoiceID 102
   VoicePitch 0.9
  }
  SoundIdentity "{6A070101A763E815}" {
   VoiceID 102
   VoicePitch -1
  }
 }
 SocialIdentity SocialIdentity "{6A0701019B838695}" {
  NamesConfig {
   "Sulton"
   "Zahid"
   "Rahmat"
   "Otabek"
   "Mushtariy"
   "Ziyod"
   "Alim"
   "Nurullo"
   "Husan"
   "Mansur"
   "Behzod"
   "Ilhom"
   "Elyor"
   "Anvar"
   "Husniddin"
   "Zafar"
   "Akmal"
   "Abidin"
   "Eldor"
   "Khakim"
   "Zayd"
   "Husayn"
   "Nusrat"
   "Kamol"
   "Zokhid"
   "Sigaretta"
   "Saddam"
   "Billy"
   "Van"
   "John"
   "Chud"
  }
  SurnamesConfig {
   "Xamidov"
   "Yusupov"
   "Yakubov"
   "Gulamov"
   "Latipov"
   "Beknazarov"
   "Mukhammadiev"
   "Kudratov"
   "Polkovnik"
   "Mansurov"
   "Ulugbek"
   "Ahmedov"
   "Yaqub"
   "Rustamov"
   "Davlatov"
   "Gairatov"
   "Kamolov"
   "Ganiev"
   "Saidov"
   "Vohidov"
   "Ibragimov"
   "Mustafoev"
   "Islomov"
   "Toshmatov"
   "Herrington"
   "Darkholme"
   "Spagistan"
   "Hussein"
   "Vogman"
  }
 }
}